apiVersion: v1
data:
  CLIENT_ID: "YOUR_GOOGLE_CLOUD_AUTH_CLIENT_ID" # Replace this in order to access the frontend
  CLIENT_SEC: "YOUR_GOOGLE_CLOUD_AUTH_CLIENT_SECRET" # Replace this in order to access the frontend
  CONTAINER_ORIGIN: http://syncserver:8080/
  FRONTEND_ORIGIN_DEV: http://localhost
  PORT: "8000"
  REDIRECT_URL_DEV: http://localhost:8000/auth/callback
  SESSION_KEY: u2IBgLagrov1Q2fi0b9o/UNpYsJMDYP5dOLWQyDZRas= # Can also generate your own and replace, using 'openssl rand -hex 32'
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-backend-env
  name: backend-env
