apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/production-tasknetwork: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: ghcr.io/ccextractor/frontend:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:80
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: frontend
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
      restartPolicy: Always
