apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: syncserver
  name: syncserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: syncserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/production-tasknetwork: "true"
        io.kompose.service: syncserver
    spec:
      containers:
        - image: ghcr.io/gothenburgbitfactory/taskchampion-sync-server:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: syncserver
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
