name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm frustrated when...
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request here.
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I've searched for existing issues
          required: true
